Update Build_susfs.yaml

diff --git a/.github/workflows/Build_susfs.yaml b/.github/workflows/Build_susfs.yaml
--- a/.github/workflows/Build_susfs.yaml
+++ b/.github/workflows/Build_susfs.yaml
@@ -236,12 +236,12 @@ jobs:
           0001-kernel-implement-susfs-v1.5.8-KernelSU-Next-v1.0.8.patch \
           0001-kernel-ksud-core_hook-migrate-ksud-execution-to-secu.patch \
         do
-         if patch -p1 < "$patch_file"; then
-          echo "✅ $patch_file applied successfully."
-         else
-          echo "❌ Patch failed to apply!"
-          exit 1
-         fi
+          if patch -p1 < "$patch_file"; then
+            echo "✅ $patch_file applied successfully."
+          else
+            echo "❌ Patch failed to apply!"
+            exit 1
+          fi
         done
 
     - name: Setup Configuration for Kernel
