Update Build_susfs.yaml

diff --git a/.github/workflows/Build_susfs.yaml b/.github/workflows/Build_susfs.yaml
--- a/.github/workflows/Build_susfs.yaml
+++ b/.github/workflows/Build_susfs.yaml
@@ -195,21 +195,15 @@ jobs:
       if: env.PATCHING_SUSFS == 'true'
       run: |
         cp backport-susfs-namespace-6.1.patch $GITHUB_WORKSPACE/kernel_workspace/android-kernel
-        cp BRICKPORT-sys_umount-refactor-to-extract-path_umount.patch $GITHUB_WORKSPACE/kernel_workspace/android-kernel
         cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
 
         echo "Applying patch..."
-        for patch_file in \
-          backport-susfs-namespace-6.1.patch \
-          BRICKPORT-sys_umount-refactor-to-extract-path_umount.patch
-        do
-          if patch -p1 < "$patch_file"; then
-            echo "✅ $patch_file applied successfully."
-          else
-            echo "❌ Patch failed to apply!"
-            exit 1
-          fi
-        done
+        if patch -p1 < backport-susfs-namespace-6.1.patch; then
+          echo "✅ Patch applied successfully."
+        else
+          echo "❌ Patch failed to apply!"
+          exit 1
+        fi
     
     - name: Download source boot image
       if: env.BUILD_BOOT_IMG == 'true'
