update

diff --git a/.github/workflows/build_bego_KSUN.yaml b/.github/workflows/build_bego_KSUN.yaml
--- a/.github/workflows/build_bego_KSUN.yaml
+++ b/.github/workflows/build_bego_KSUN.yaml
@@ -1,15 +1,15 @@
-name: Build RKSU on Nova & power
+name: Build KSUN BEGONIA
 on:
   workflow_dispatch:
     inputs:
       kernel_source_branch:
         description: 'Kernel source branch'
         required: false
-        default: 'fifteen-fixed-ksu'
+        default: 'begonia'
         type: choice
         options:
-          - 'fifteen-fixed-ksu'
-          - 'bka'
+          - 'begonia-r-oss'
+          - 'begonia'
       enable_kernelsu:
         description: 'Enable KernelSU integration?'
         required: true
@@ -25,6 +25,7 @@ on:
         type: choice
         options:
           - 'susfs-rksu-master'
+          - 'main'
           - 'legacy'
       repo_ksu:
         description: 'Repo for KernelSU (owner/repo)'
@@ -33,6 +34,8 @@ on:
         type: choice
         options:
           - 'rsuntk/KernelSU'
+          - 'hakuna77/KernelSU'
+          - 'hakuna77/KernelSU-Next'
           - 'KernelSU-Next/KernelSU-Next'
       patching_susfs:
         description: 'Enable patch susfs Kernel?'
@@ -45,11 +48,12 @@ on:
       manual_hook:
         description: 'Select Manual Hook'
         required: true
-        default: '0001-scope-minimized-manual-hooks-v1.4.patch'
+        default: '0001-scope-manual-hook-1.6.patch'
         type: choice
         options:
-          - '0001-scope-minimized-manual-hooks-v1.4.patch'
-          - '0001-scope-minimized-manual-hooks-v1.5.patch'
+          - '0001-scope-manual-hook-1.6.patch'
+          - '0001-scope-minimized-manual-hooks-v1.6-do_execve.patch'
+          - 'None'
       select_version_patch_susfs_to_kernel:
         description: 'Select SUSFS PATCH Into Kernel'
         required: true
@@ -58,6 +62,10 @@ on:
         options:
           - '0001-susfs2.0.0.patch'
           - '0001-v2.0.0.patch'
+          - '0001-susfs-v2.0.0-latest-commit-ida-new-api.patch'
+          - '0001-susfs-v2.0.0-manual-hook-not-incluced.patch'
+          - '0001-susfs-v2.0.0-KSUN.patch'
+          - '0001-susfs-v2.0.0-try_umount.patch'
       patching_ksun:
         description: 'Enable patch susfs KernelSU-Next?'
         required: true
@@ -73,6 +81,9 @@ on:
         type: choice
         options:
           - 'test.patch'
+          - '0001-susfs-v2.0.0-ksun.patch'
+          - '0001-fix-build-error.patch'
+          - '0001-avc-v2.patch'
       build_boot_img:
         description: 'enable BUILD BOOT IMG'
         required: true
@@ -188,17 +199,17 @@ jobs:
       uses: actions/cache@v3
       with:
         path: ${{ github.workspace }}/kernel_workspace/clang-aosp
-        key: clang-${{ env.CLANG_BRANCH }}-${{ env.CLANG_VERSION }}
+        key: clang-android11-release-r383902b
         restore-keys: |
-          clang-android16-release-
+          clang-android11-release-
     
     - name: Download Clang-aosp
       if: steps.cache-clang.outputs.cache-hit != 'true' && env.USE_CUSTOM_CLANG != 'true'
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace
         mkdir clang-aosp
-        wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/${{ env.CLANG_BRANCH }}/clang-${{ env.CLANG_VERSION }}.tar.gz
-        tar -C clang-aosp/ -zxvf clang-${{ env.CLANG_VERSION }}.tar.gz
+        wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android11-release/clang-r383902b.tar.gz
+        tar -C clang-aosp/ -zxvf clang-r383902b.tar.gz
 
     - name: Download Custom-Clang
       if: env.USE_CUSTOM_CLANG == 'true'
@@ -273,19 +284,13 @@ jobs:
     - name: Download kernel source
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace
-        if [[ ${{ env.KERNEL_SOURCE_BRANCH }} == 'fifteen-fixed-ksu' ]]; then 
-          git clone --recursive https://github.com/hakuna77/kernel_xiaomi_mt6785.git -b ${{ env.KERNEL_SOURCE_BRANCH }} android-kernel --depth=1
-        fi
-        
-        if [[ ${{ env.KERNEL_SOURCE_BRANCH }} == 'bka' ]]; then 
-          git clone --recursive https://github.com/hakuna77/Power.git -b ${{ env.KERNEL_SOURCE_BRANCH }} android-kernel --depth=1
-        fi
-        
+        git clone --recursive https://github.com/hakuna77/kernel_stock.git -b ${{ env.KERNEL_SOURCE_BRANCH }} android-kernel --depth=1
         if [[ ${{ env.ADD_LOCALVERSION_TO_FILENAME }} == 'true' ]]; then
           echo "LOCALVERSION=$(cat android-kernel/localversion)" >> $GITHUB_ENV
         else
           echo "LOCALVERSION=" >> $GITHUB_ENV
         fi
+    
     - name: Patching susfs
       if: env.PATCHING_SUSFS == 'true'
       run: |
@@ -295,9 +300,98 @@ jobs:
 
         echo "Applying patch..."
         
-        if [ "${{ env.KERNEL_SOURCE_BRANCH }}" == "bka" ]; then
+        if [[ "${{ env.KERNEL_SOURCE_BRANCH }}" == "begonia" && "${{ env.MANUAL_HOOK }}" == "0001-scope-manual-hook-1.6.patch" ]]; then
           for patch_file in \
-            add-slow_avc_audit-hook.patch
+            0002-BACKPORT-ptrace-Move-setting-clearing.patch \
+            0003-BACKPORT-fs-namespace.c-path_umount-5.10.9.patch \
+            0001-inotify-show-inotify-mask-flags-in-proc-fdinfo.patch \
+            0001-BACKPORT-stat-from-k-5.10.y.patch \
+            0006-BACKPORT-maccess-rename-strncpy_from_unsafe_user-to-.patch \
+            0001-stat-fix-inconsistency-between-struct-stat-and-struc.patch \
+            0001-BACKPORT-seccomp-add-filter_count-field-for-KernelSU.patch \
+            0010-BACKPORT-vfs-syscall-Add-move_mount-2-to-move-mounts.patch \
+            0011-BACKPORT-arm-arm64-wire-up-backported-sys_move_mount.patch \
+            0001-backport-test.patch \
+            ${{ env.MANUAL_HOOK }} \
+            add-slow_avc_audit-hook.patch \
+            0001-upstream-avc.patch
+          do
+            if patch -p1 < "$patch_file"; then
+              echo "✅ $patch_file applied successfully."
+            else
+              echo "❌ Patch failed to apply!"
+              exit 1
+            fi
+          done
+        fi
+        
+        if [[ "${{ env.KERNEL_SOURCE_BRANCH }}" == "begonia" && "${{ env.MANUAL_HOOK }}" == "None" ]]; then
+          for patch_file in \
+            0002-BACKPORT-ptrace-Move-setting-clearing.patch \
+            0003-BACKPORT-fs-namespace.c-path_umount-5.10.9.patch \
+            0001-inotify-show-inotify-mask-flags-in-proc-fdinfo.patch \
+            0001-BACKPORT-stat-from-k-5.10.y.patch \
+            0006-BACKPORT-maccess-rename-strncpy_from_unsafe_user-to-.patch \
+            0001-BACKPORT-proc-less-memory-for-proc-map_files-readdir.patch \
+            0001-stat-fix-inconsistency-between-struct-stat-and-struc.patch \
+            0001-BACKPORT-seccomp-add-filter_count-field-for-KernelSU.patch \
+            0010-BACKPORT-vfs-syscall-Add-move_mount-2-to-move-mounts.patch \
+            0011-BACKPORT-arm-arm64-wire-up-backported-sys_move_mount.patch \
+            0001-backport-test.patch \
+            ${{ env.SELECT_VERSION_PATCH_SUSFS_TO_KERNEL }}
+          do
+            if patch -p1 < "$patch_file"; then
+              echo "✅ $patch_file applied successfully."
+            else
+              echo "❌ Patch failed to apply!"
+              exit 1
+            fi
+          done
+        fi
+        
+        if [[ "${{ env.KERNEL_SOURCE_BRANCH }}" == "begonia" && "${{ env.SELECT_VERSION_PATCH_SUSFS_TO_KERNEL }}" == "0001-susfs-v2.0.0-manual-hook-not-incluced.patch" ]]; then
+          for patch_file in \
+            0002-BACKPORT-ptrace-Move-setting-clearing.patch \
+            0003-BACKPORT-fs-namespace.c-path_umount-5.10.9.patch \
+            0001-inotify-show-inotify-mask-flags-in-proc-fdinfo.patch \
+            0001-BACKPORT-stat-from-k-5.10.y.patch \
+            0006-BACKPORT-maccess-rename-strncpy_from_unsafe_user-to-.patch \
+            0001-BACKPORT-proc-less-memory-for-proc-map_files-readdir.patch \
+            0001-stat-fix-inconsistency-between-struct-stat-and-struc.patch \
+            0001-BACKPORT-seccomp-add-filter_count-field-for-KernelSU.patch \
+            0010-BACKPORT-vfs-syscall-Add-move_mount-2-to-move-mounts.patch \
+            0011-BACKPORT-arm-arm64-wire-up-backported-sys_move_mount.patch \
+            0001-backport-test.patch \
+            ${{ env.MANUAL_HOOK }} \
+            ${{ env.SELECT_VERSION_PATCH_SUSFS_TO_KERNEL }} \
+            add-slow_avc_audit-hook.patch \
+            0001-upstream-avc.patch
+          do
+            if patch -p1 < "$patch_file"; then
+              echo "✅ $patch_file applied successfully."
+            else
+              echo "❌ Patch failed to apply!"
+              exit 1
+            fi
+          done
+        fi
+        
+        if [[ "${{ env.KERNEL_SOURCE_BRANCH }}" == "begonia" && "${{ env.SELECT_VERSION_PATCH_SUSFS_TO_KERNEL }}" == "0001-susfs-v2.0.0-try_umount.patch" ]]; then
+          for patch_file in \
+            0001-cred-add-get_cred_rcu.patch \
+            0002-BACKPORT-ptrace-Move-setting-clearing.patch \
+            0003-BACKPORT-fs-namespace.c-path_umount-5.10.9.patch \
+            0001-inotify-show-inotify-mask-flags-in-proc-fdinfo.patch \
+            0001-BACKPORT-stat-from-k-5.10.y.patch \
+            0006-BACKPORT-maccess-rename-strncpy_from_unsafe_user-to-.patch \
+            0001-BACKPORT-proc-less-memory-for-proc-map_files-readdir.patch \
+            0001-stat-fix-inconsistency-between-struct-stat-and-struc.patch \
+            0001-BACKPORT-seccomp-add-filter_count-field-for-KernelSU.patch \
+            0010-BACKPORT-vfs-syscall-Add-move_mount-2-to-move-mounts.patch \
+            0011-BACKPORT-arm-arm64-wire-up-backported-sys_move_mount.patch \
+            0001-backport-test.patch \
+            ${{ env.MANUAL_HOOK }} \
+            ${{ env.SELECT_VERSION_PATCH_SUSFS_TO_KERNEL }}
           do
             if patch -p1 < "$patch_file"; then
               echo "✅ $patch_file applied successfully."
@@ -391,8 +485,6 @@ jobs:
     - name: Setup Configuration for Kernel
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
-        BUILD_DEF=arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
-        STOCK_DEF=arch/${{ env.ARCH }}/configs/stock_defconfig
         if [ ${{ env.ENABLE_KERNELSU }} = true ]; then
             if grep -q "CONFIG_KSU" arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}; then
                 sed -i 's/# CONFIG_KSU is not set/CONFIG_KSU=y/g' arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
@@ -413,6 +505,11 @@ jobs:
                 echo "CONFIG_KSU_MANUAL_HOOK=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
             fi
         fi
+        
+        if [ ${{ env.SELECT_VERSION_PATCH_SUSFS_TO_KERNEL }} = "0001-susfs-v2.0.0-try_umount.patch" ]; then
+            echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
+        fi
+        
         if [ ${{ env.ADD_KPROBES_CONFIG }} = true -a ${{ env.APPLY_KSU_PATCH }} != true ]; then
             echo "CONFIG_MODULES=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
             echo "CONFIG_KPROBES=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
@@ -420,23 +517,8 @@ jobs:
             echo "CONFIG_KPROBE_EVENTS=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
         fi
         if [ ${{ env.ADD_OVERLAYFS_CONFIG }} = true ]; then
-            for FILE in "$BUILD_DEF" "$STOCK_DEF"; do
-              [ -f "$FILE" ] || continue
-              echo "🔧 Editing $FILE"
-              for opt in CONFIG_OVERLAY_FS CONFIG_TMPFS_XATTR; do
-                if grep -q "^${opt}=y" "$FILE"; then
-                  echo "✔ ${opt} already enabled, skip"
-                else
-                  sed -i "/^# ${opt} is not set/d" "$FILE"
-                  sed -i "/^${opt}=.*/d" "$FILE"
-                  echo "${opt}=y" >> "$FILE"
-                  echo "➕ Enabled ${opt}"
-                fi
-              done
-            done
-            echo "✅ OVERLAYFS & TMPFS enabled (begonia_user_defconfig + stock_defconfig)"
-        else
-            echo "❌ OVERLAYFS & TMPFS disabled"
+            echo "CONFIG_OVERLAY_FS=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
+            echo "CONFIG_TMPFS_XATTR=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
         fi
         if [ ${{ env.DISABLE-LTO }} = true ]; then
             sed -i 's/CONFIG_LTO=y/CONFIG_LTO=n/' arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
@@ -448,21 +530,8 @@ jobs:
             echo "CONFIG_CC_WERROR=n" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
         fi
         if [ ${{ env.ADD_KPM }} = true ]; then
-            for FILE in "$BUILD_DEF" "$STOCK_DEF"; do
-              [ -f "$FILE" ] || continue
-              echo "🔧 Editing $FILE"
-              for opt in CONFIG_KALLSYMS_ALL CONFIG_KALLSYMS_BASE_RELATIVE; do
-                if grep -q "^${opt}=y" "$FILE"; then
-                  echo "✔ ${opt} already enabled, skip"
-                else
-                  sed -i "/^# ${opt} is not set/d" "$FILE"
-                  sed -i "/^${opt}=.*/d" "$FILE"
-                  echo "${opt}=y" >> "$FILE"
-                  echo "➕ Enabled ${opt}"
-                fi
-              done
-            done
-            echo "✅ KPM enabled (begonia_user_defconfig + stock_defconfig)"
+            echo "CONFIG_KALLSYMS_ALL=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
+            echo "✅ KPM enabled"
         else
             echo "❌ KPM disabled"
         fi
@@ -471,7 +540,7 @@ jobs:
       if: env.ENABLE_CCACHE == 'true'
       uses: hendrikmuhs/ccache-action@v1.2
       with:
-        key: build-kernel-${{ env.DEVICE }}${{ env.LOCALVERSION }}${{ env.UPLOADNAME }}
+        key: build-kernel-stock-${{ env.DEVICE }}${{ env.LOCALVERSION }}${{ env.UPLOADNAME }}
         max-size: 2G
         
     - name: Detect Compiler Version
