update

diff --git a/.github/workflows/build_rksu.yaml b/.github/workflows/build_rksu.yaml
--- a/.github/workflows/build_rksu.yaml
+++ b/.github/workflows/build_rksu.yaml
@@ -374,6 +374,32 @@ jobs:
           done
         fi
         
+        if [[ "${{ env.KERNEL_SOURCE_BRANCH }}" == "begonia" && "${{ env.SELECT_VERSION_PATCH_SUSFS_TO_KERNEL }}" == "0001-susfs-v2.0.0-try_umount.patch" ]]; then
+          for patch_file in \
+            0001-cred-add-get_cred_rcu.patch \
+            0002-BACKPORT-ptrace-Move-setting-clearing.patch \
+            0003-BACKPORT-fs-namespace.c-path_umount-5.10.9.patch \
+            0001-inotify-show-inotify-mask-flags-in-proc-fdinfo.patch \
+            0001-BACKPORT-stat-from-k-5.10.y.patch \
+            0006-BACKPORT-maccess-rename-strncpy_from_unsafe_user-to-.patch \
+            0001-BACKPORT-proc-less-memory-for-proc-map_files-readdir.patch \
+            0001-stat-fix-inconsistency-between-struct-stat-and-struc.patch \
+            0001-BACKPORT-seccomp-add-filter_count-field-for-KernelSU.patch \
+            0010-BACKPORT-vfs-syscall-Add-move_mount-2-to-move-mounts.patch \
+            0011-BACKPORT-arm-arm64-wire-up-backported-sys_move_mount.patch \
+            0001-backport-test.patch \
+            ${{ env.MANUAL_HOOK }} \
+            ${{ env.SELECT_VERSION_PATCH_SUSFS_TO_KERNEL }}
+          do
+            if patch -p1 < "$patch_file"; then
+              echo "✅ $patch_file applied successfully."
+            else
+              echo "❌ Patch failed to apply!"
+              exit 1
+            fi
+          done
+        fi
+        
         if [ "${{ env.KERNEL_SOURCE_BRANCH }}" == "begonia-r-oss" ]; then
           for patch_file in \
             0001-BACKPORT-proc-less-memory-for-proc-map_files-readdir.patch \
