Update Build_susfs.yaml

diff --git a/.github/workflows/Build_susfs.yaml b/.github/workflows/Build_susfs.yaml
--- a/.github/workflows/Build_susfs.yaml
+++ b/.github/workflows/Build_susfs.yaml
@@ -196,15 +196,25 @@ jobs:
       if: env.PATCHING_SUSFS == 'true'
       run: |
         cp 0001-BACKPORT-SUSFS-v1.5.8.patch $GITHUB_WORKSPACE/kernel_workspace/android-kernel
+        cp Android.patch $GITHUB_WORKSPACE/kernel_workspace/android-kernel
+        cp Android1.patch $GITHUB_WORKSPACE/kernel_workspace/android-kernel
+        cp brickport.patch $GITHUB_WORKSPACE/kernel_workspace/android-kernel
         cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
 
         echo "Applying patch..."
-        if patch -p1 < 0001-BACKPORT-SUSFS-v1.5.8.patch; then
-          echo "✅ Patch applied successfully."
-        else
-          echo "❌ Patch failed to apply!"
-          exit 1
-        fi
+        for patch_file in \
+          0001-BACKPORT-SUSFS-v1.5.8.patch \
+          Android.patch \
+          Android1.patch \
+          brickport.patch
+        do
+          if patch -p1 < "$patch_file"; then
+            echo "✅ $patch_file applied successfully."
+          else
+            echo "❌ Patch failed to apply!"
+            exit 1
+          fi
+        done
     
     - name: Download source boot image
       if: env.BUILD_BOOT_IMG == 'true'
