Update Build_susfs.yaml

diff --git a/.github/workflows/Build_susfs.yaml b/.github/workflows/Build_susfs.yaml
--- a/.github/workflows/Build_susfs.yaml
+++ b/.github/workflows/Build_susfs.yaml
@@ -203,12 +203,13 @@ jobs:
           backport-susfs-namespace-6.1.patch \
           BRICKPORT-sys_umount-refactor-to-extract-path_umount.patch
         do
-        if patch -p1 < "$patch_file"; then
-          echo "✅ $patch_file applied successfully."
-        else
-          echo "❌ Patch failed to apply!"
-          exit 1
-        fi
+          if patch -p1 < "$patch_file"; then
+            echo "✅ $patch_file applied successfully."
+          else
+            echo "❌ Patch failed to apply!"
+            exit 1
+          fi
+        done
     
     - name: Download source boot image
       if: env.BUILD_BOOT_IMG == 'true'
