update

diff --git a/.github/workflows/suki_new.yaml b/.github/workflows/suki_new.yaml
--- a/.github/workflows/suki_new.yaml
+++ b/.github/workflows/suki_new.yaml
@@ -62,22 +62,21 @@ on:
           - '0001-susfs-v1.5.11.patch'
           - '0001-susfs-v1.5.12.patch'
           - '0001-susfs-v1.5.12-test.patch'
-      add_kpm:
-        description: 'Enable KPM?'
+      patching_sukisu:
+        description: 'Enable patch SUKISU?'
         required: true
-        default: 'true'
+        default: 'false'
         type: choice
         options:
           - 'true'
           - 'false'
-      patching_kpm:
-        description: 'patching kpm'
+      select_patch:
+        description: 'Select PATCH into KSUN'
         required: true
-        default: 'true'
+        default: '0001-fix-sukisu-for-non-gki.patch'
         type: choice
         options:
-          - 'true'
-          - 'false'
+          - '0001-fix-sukisu-for-non-gki.patch'
       build_boot_img:
         description: 'enable BUILD BOOT IMG'
         required: true
@@ -96,8 +95,8 @@ env:
   PATCHING_SUSFS: ${{ github.event.inputs.patching_susfs }}
   MANUAL_HOOK: ${{ github.event.inputs.manual_hook }}
   SELECT_VERSION_PATCH_SUSFS_TO_KERNEL: ${{ github.event.inputs.select_version_patch_susfs_to_kernel }}
-  ADD_KPM: ${{ github.event.inputs.add_kpm }}
-  PATCHING_KPM: ${{ github.event.inputs.patching_kpm }}
+  PATCHING_SUKISU: ${{ github.event.inputs.patching_sukisu }}
+  SELECT_PATCH: ${{ github.event.inputs.select_patch }}
   BUILD_BOOT_IMG: ${{ github.event.inputs.build_boot_img }}
   
 jobs:
@@ -150,6 +149,8 @@ jobs:
             KSU_EXPECTED_SIZE
             KSU_EXPECTED_HASH
             REMOVE_UNUSED_PACKAGES
+            ADD_KPM
+            PATCHING_KPM
         )
 
         for CONFIG in "${CONFIG_LIST[@]}"; do
@@ -343,7 +344,26 @@ jobs:
         echo "UPLOADNAME=-KernelSU_$KSU_VERSION" >> $GITHUB_ENV
         echo "KSU_DIR=$KSU_DIR" >> $GITHUB_ENV
         
+    - name: Patching SUKISU
+      if: env.PATCHING_SUKISU == 'true'
+      run: |
+        KSU_DIR="${{ env.KSU_DIR }}"
+        cp kernelsu_patch/*.patch $GITHUB_WORKSPACE/kernel_workspace/android-kernel/$KSU_DIR
+        
+        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel/$KSU_DIR
 
+        echo "Applying patch..."
+        for patch_file in \
+          ${{ env.SELECT_PATCH }}
+        do
+          if patch -p1 < "$patch_file"; then
+            echo "✅ $patch_file applied successfully."
+          else
+            echo "❌ Patch failed to apply!"
+            exit 1
+          fi
+        done
+    
     - name: Setup Configuration for Kernel
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
@@ -392,7 +412,7 @@ jobs:
         if [ ${{ env.DISABLE_CC_WERROR }} = true ]; then
             echo "CONFIG_CC_WERROR=n" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
         fi
-        if [ ${{ env.ADD_KPM }} = "true" ]; then
+        if [ ${{ env.ADD_KPM }} = true ]; then
             echo "CONFIG_KPM=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
             echo "CONFIG_KALLSYMS_ALL=y" >> arch/${{ env.ARCH }}/configs/${{ env.KERNEL_CONFIG }}
             echo "✅ KPM enabled"
